version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - 'python'
      - 'manage.py'
      - 'runserver'
      - '0.0.0.0:8000'
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./uploads:/app/uploads

  database:
    image: postgres:16.2-alpine3.19
    user: root
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  worker:
    build:
      dockerfile: ./Dockerfile
    command:
      - 'celery'
      - '-A'
      - 'test_site'
      - 'worker'
      - '-l'
      - 'info'
    links:
      - redis
      - app
    env_file:
      - .env
    restart: always
    depends_on:
      - database
    volumes:
      - ./uploads:/app/uploads
