# Generated by Django 5.0.2 on 2024-02-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
